### ISSUE TITLE
DataCenters Stats??

### ISSUE THREAD

**Issue by pr-acassera** [cblomart/vsphere-graphite#19] opened 2017-10-16 23:58 UTC
If I have different datacenters in the hierarchy for the vcenter instance, do I need to specify the datacenter to get stats for objects in a specific datacenter?  In my lab I able to poll stats but I have a single vcenter with a single DC.  In another environment I cannot poll stats I get 0 query results from the vcenter instance.  The only difference is that I have multiple datacenters defined on the one vcenter server where I get 0 query results.

**Comment by cblomart** [comment] 2017-10-17 06:45
You should not need to provide a datacenter.
Vsphere-graphite will poll for all defined stats an objects defined in the config.

I need to check if the datacenter is part of the tags (I don’t think so): you could the query vms from a specific datacenter.

Envoyé de mon iPhone

**Comment by pr-acassera** [comment] 2017-10-17 15:10
okay I must be missing something else.

**Comment by cblomart** [comment] 2017-10-17 17:03
Do you have a sample of your config? 
Could you tel which rights you set the vsphere-graphite user and at which level?

**Comment by pr-acassera** [comment] 2017-10-17 17:31
By the way thank you for writing the code and making is available.  Below is the json file.  I am using the administrator account right now.  I reduced the metrics to just try to get data.  Below that is the response I get.

{
	"Domain": ".vsphere.local",
	"Interval": 60,
	"VCenters": [
		{ "Username": "administrator@vsphere.local", "Password": "Password", "Hostname": "10.0.153.225" }

	],
	"Backend":{
		"Type": "influxdb",
		"Hostname": "",
		"Username": "vm",
		"Password": "password",
		"Database": "vmware_performance",
		"Port": 8086
	},
	"Metrics": [
		{
			"ObjectType": [ "VirtualMachine", "HostSystem" ],
			"Definition": [
				{ "Metric": "cpu.usage.average", "Instances": ""}
			]
		}
	]
}

root@monitor-host:/# vsphere-graphite
2017/10/17 13:28:21 Starting daemon: vsphere-graphite
2017/10/17 13:28:21 connecting to vcenter: 10.0.153.225
2017/10/17 13:28:21 Intializing influxdb backend
2017/10/17 13:28:21 Retrieving metrics
2017/10/17 13:28:21 Setting up query inventory of vcenter:  10.0.153.225
2017/10/17 13:28:21 connecting to vcenter: 10.0.153.225
2017/10/17 13:28:21 Issuing 194 queries to vcenter 10.0.153.225 requesting 194 metrics.
2017/10/17 13:28:22 No result returned by queries.
2017/10/17 13:28:22 Got 0 resluts from 10.0.153.225 with 0 values
2017/10/17 13:28:22 disconnecting from vcenter: 10.0.153.225

**Comment by cblomart** [comment] 2017-10-17 20:20
Apparently duplicate of #18 

As it doesn't happen with the vcenter i have: i wasn't able to reproduce it somewhere (time & ressources).

Seems like it will be needed somehow...
If anyone knows of a publicly availabale vcenter ;-P

**Comment by pr-acassera** [comment] 2017-10-18 15:29
From my working vcenter with a single DC and the vcenter that I cannot get data from I get different results on govc:

root@ubuntu-1:/home/# govc ls
/Lab-DC/vm
/Lab-DC/network
/Lab-DC/host
/Lab-DC/datastore

root@monitor-host:/etc# govc ls
/BethPage
/WebAir

It is expecting the DC in the query to get the individual component data?

**Comment by pr-acassera** [comment] 2017-10-19 13:27
Tested against another environment with a single datacenter running 6.5 and it polled fine.

**Comment by cblomart** [comment] 2017-10-19 19:31
What was the version of vcenter before?

Envoyé de mon iPhone

**Comment by pr-acassera** [comment] 2017-10-19 20:18
Here is what I tested so far.  I am going to add an additional DC in the lab and see what happens.

Tested single DC 6.0 is working in the lab
Tested two DC 6.0 no query results.
Tested single DC 6.5 working fine.

**Comment by pr-acassera** [comment] 2017-10-22 19:56
Sorry to have wasted your time over the past few weeks.  Looks like the infrastructure was pointing to older dated time servers.  Update the time servers and now I am getting data.  There was a time skew.  Thank you very much for your help.

**Comment by cblomart** [comment] 2017-10-23 15:40
Didn’t do much.

Happy that this works!!! :-)

I shall ask in the linked post if time is synced.
(Or I could request server time on init to account for time skew)

**Comment by pr-acassera** [comment] 2017-10-24 17:28
I would suggest making the time skew request.  So if the monitor instance or server is out of time skew with the server you might get a message or log entry indicating this.

**Closed** 2017-10-25 15:02 UTC
