### ISSUE TITLE
got panic: runtime error: invalid memory address or nil pointer dereference while run

### ISSUE THREAD

**Issue by ridhoyp** [cblomart/vsphere-graphite#8] opened 2017-05-17 12:52 UTC
Hi, 

i just run it, and got panic while run, but already return some value

2017/05/17 19:44:22 Starting daemon: vsphere-graphite
2017/05/17 19:44:22 connecting to vcenter: vcenter
2017/05/17 19:44:22 Appended metric group with cpu.usage.average identified by 2 to vcenter vcenter for VirtualMachine
2017/05/17 19:44:22 Appended metric group with cpu.usage.average identified by 2 to vcenter vcenter for HostSystem
2017/05/17 19:44:22 Appended metric cpu.usage.maximum identified by 4 to vcenter vcenter for VirtualMachine
2017/05/17 19:44:22 Appended metric cpu.usage.maximum identified by 4 to vcenter vcenter for HostSystem
2017/05/17 19:44:22 Appended metric cpu.usagemhz.average identified by 6 to vcenter vcenter for VirtualMachine
2017/05/17 19:44:22 Appended metric cpu.usagemhz.average identified by 6 to vcenter vcenter for HostSystem
2017/05/17 19:44:22 Appended metric cpu.usagemhz.maximum identified by 8 to vcenter vcenter for VirtualMachine
2017/05/17 19:44:22 Appended metric cpu.usagemhz.maximum identified by 8 to vcenter vcenter for HostSystem
2017/05/17 19:44:22 Appended metric mem.usage.average identified by 24 to vcenter vcenter for VirtualMachine
2017/05/17 19:44:22 Appended metric mem.usage.average identified by 24 to vcenter vcenter for HostSystem
2017/05/17 19:44:22 Appended metric mem.usage.maximum identified by 26 to vcenter vcenter for VirtualMachine
2017/05/17 19:44:22 Appended metric mem.usage.maximum identified by 26 to vcenter vcenter for HostSystem
2017/05/17 19:44:22 Appended metric mem.active.average identified by 33 to vcenter vcenter for VirtualMachine
2017/05/17 19:44:22 Appended metric mem.active.average identified by 33 to vcenter vcenter for HostSystem
2017/05/17 19:44:22 Appended metric mem.active.maximum identified by 35 to vcenter vcenter for VirtualMachine
2017/05/17 19:44:22 Appended metric mem.active.maximum identified by 35 to vcenter vcenter for HostSystem
2017/05/17 19:44:22 Appended metric mem.vmmemctl.average identified by 90 to vcenter vcenter for VirtualMachine
2017/05/17 19:44:22 Appended metric mem.vmmemctl.average identified by 90 to vcenter vcenter for HostSystem
2017/05/17 19:44:22 Appended metric mem.vmmemctl.maximum identified by 92 to vcenter vcenter for VirtualMachine
2017/05/17 19:44:22 Appended metric mem.vmmemctl.maximum identified by 92 to vcenter vcenter for HostSystem
2017/05/17 19:44:22 Appended metric mem.consumed.average identified by 98 to vcenter vcenter for VirtualMachine
2017/05/17 19:44:22 Appended metric mem.consumed.average identified by 98 to vcenter vcenter for HostSystem
2017/05/17 19:44:22 Appended metric mem.consumed.maximum identified by 100 to vcenter vcenter for VirtualMachine
2017/05/17 19:44:22 Appended metric mem.consumed.maximum identified by 100 to vcenter vcenter for HostSystem
2017/05/17 19:44:22 Appended metric disk.maxTotalLatency.latest identified by 133 to vcenter vcenter for HostSystem
2017/05/17 19:44:22 Appended metric disk.numberReadAveraged.average identified by 136 to vcenter vcenter for HostSystem
2017/05/17 19:44:22 Appended metric disk.numberWriteAveraged.average identified by 137 to vcenter vcenter for HostSystem
2017/05/17 19:44:22 Appended metric virtualDisk.numberReadAveraged.average identified by 171 to vcenter vcenter for VirtualMachine
2017/05/17 19:44:22 Appended metric virtualDisk.numberWriteAveraged.average identified by 172 to vcenter vcenter for VirtualMachine
2017/05/17 19:44:22 Appended metric virtualDisk.totalReadLatency.average identified by 175 to vcenter vcenter for VirtualMachine
2017/05/17 19:44:22 Appended metric virtualDisk.totalWriteLatency.average identified by 176 to vcenter vcenter for VirtualMachine
2017/05/17 19:44:22 Appended metric cpu.totalCapacity.average identified by 395 to vcenter vcenter for VirtualMachine
2017/05/17 19:44:22 Appended metric cpu.totalCapacity.average identified by 395 to vcenter vcenter for HostSystem
2017/05/17 19:44:22 Appended metric mem.totalCapacity.average identified by 419 to vcenter vcenter for VirtualMachine
2017/05/17 19:44:22 Appended metric mem.totalCapacity.average identified by 419 to vcenter vcenter for HostSystem
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x4870ff]

goroutine 1 [running]:
panic(0xa93d60, 0xc42000c0f0)
        /usr/local/go/src/runtime/panic.go:500 +0x1a1
log.(*Logger).Output(0x0, 0x2, 0xc420216300, 0x12, 0x0, 0x0)
        /usr/local/go/src/log/log.go:147 +0x6f
log.(*Logger).Println(0x0, 0xc42029b858, 0x1, 0x1)
        /usr/local/go/src/log/log.go:182 +0x6a
github.com/cblomart/vsphere-graphite/backend.(*Backend).Init(0xc4200c61c8, 0xc420010870, 0xc4200108c0, 0x4, 0xc420010870)
        /var/lib/vmware/src/github.com/cblomart/vsphere-graphite/backend/backend.go:77 +0x15c
main.(*Service).Manage(0xc42029be78, 0x0, 0x0, 0x0, 0x0)
        /var/lib/vmware/src/github.com/cblomart/vsphere-graphite/vsphere-graphite.go:117 +0x569
main.main()
        /var/lib/vmware/src/github.com/cblomart/vsphere-graphite/vsphere-graphite.go:176 +0x10f

**Comment by cblomart** [comment] 2017-05-17 16:25
I think it is due to an error in the sample configuratin file.
Since the introduction of multiple backend types i updated the "graphite" property to "backend" and included a subproperty of backend mentionning the type ("graphite" or "influxdb").

I updated the sample configuration (for graphite). Influxdb will require more information (username, password, database).

See issue #5 

Cédric

**Comment by ridhoyp** [comment] 2017-05-18 01:01
Hi ,

Thanks for reply,

i already change the vsphere-graphite.json but still have memory problem , when i using influxdb i just got the list of virtual machine name and vcenter, the metrics is empty

Regards,
RidhoYP

**Comment by cblomart** [comment] 2017-05-18 07:48
Can you check the pre release i made (0.2c) and upload a trace of the logs?
I corrected a missue of an unitilialized variable in this version (error logger).

**Comment by ridhoyp** [comment] 2017-05-20 23:58
Hi 

After i repulled the source

it got the metrics, but the backend , 

2017/05/21 06:53:41 Appended metric cpu.totalCapacity.average identified by 395 to vcenter 10.16.99.20 for VirtualMachine
2017/05/21 06:53:41 Appended metric cpu.totalCapacity.average identified by 395 to vcenter 10.16.99.20 for HostSystem
2017/05/21 06:53:41 Appended metric mem.totalCapacity.average identified by 419 to vcenter 10.16.99.20 for VirtualMachine
2017/05/21 06:53:41 Appended metric mem.totalCapacity.average identified by 419 to vcenter 10.16.99.20 for HostSystem
2017/05/21 06:53:41 Backend  unknown.
2017/05/21 06:53:41 Could not initialize backend
Error:  Backend  unknown.


here is the json configuration

{
  "Domain": ".jne.co.id",
  "Interval": 60,
  "VCenters": [
    { "Username": "administrator@test", "Password": "test/4u", "Hostname": "vcenter"  }
  ],
  "Graphite": {
    "Hostname": "localhost",
    "Port": 2003
  },
  "Metrics": [
    {
      "ObjectType": [ "VirtualMachine", "HostSystem" ],
      "Definition": [
        { "Metric": "cpu.usage.average", "Instances": "" },
        { "Metric": "cpu.usage.maximum", "Instances": "" },
        { "Metric": "cpu.usagemhz.average", "Instances": "" },
        { "Metric": "cpu.usagemhz.maximum", "Instances": "" },
        { "Metric": "cpu.totalCapacity.average", "Instances": "" },
        { "Metric": "mem.usage.average", "Instances": "" },
        { "Metric": "mem.usage.maximum", "Instances": "" },
        { "Metric": "mem.consumed.average", "Instances": "" },
        { "Metric": "mem.consumed.maximum", "Instances": "" },
        { "Metric": "mem.active.average", "Instances": "" },
        { "Metric": "mem.active.maximum", "Instances": "" },
        { "Metric": "mem.vmmemctl.average", "Instances": "" },
        { "Metric": "mem.vmmemctl.maximum", "Instances": "" },
        { "Metric": "mem.totalCapacity.average", "Instances": "" }
      ]
    },
    {
      "ObjectType": [ "VirtualMachine" ],
      "Definition": [
        { "Metric": "virtualDisk.totalWriteLatency.average", "Instances": "*" },
        { "Metric": "virtualDisk.totalWriteLatency.maximum", "Instances": "*" },
        { "Metric": "virtualDisk.totalReadLatency.average", "Instances": "*" },
        { "Metric": "virtualDisk.totalReadLatency.maximum", "Instances": "*" },
        { "Metric": "virtualDisk.numberReadAveraged.average", "Instances": "*" },
        { "Metric": "virtualDisk.numberWriteAveraged.average", "Instances": "*" }
      ]
    },
    {
      "ObjectType": [ "HostSystem" ],
      "Definition": [
        { "Metric": "disk.maxTotalLatency.latest", "Instances": "" },
        { "Metric": "disk.numberReadAveraged.average", "Instances": "*" },
        { "Metric": "disk.numberWriteAveraged.average", "Instances": "*" }
      ]
    }
  ]
}

**Comment by cblomart** [comment] 2017-05-21 04:01
I tought you wanted to use influx db...

Anyways the configuration file semantic had changed since the introduction of multiple backends.

The following :
"Graphite": {
"Hostname": "localhost",
"Port": 2003
},

Needs to be changed to:
"Backend": {
"Type": "graphite"
"Hostname": "localhost",
"Port": 2003
},



Envoyé de mon iPhone

**Comment by ridhoyp** [comment] 2017-05-21 13:52
Hi,

Its worked like a charm :)

btw can i add metrics like this 

},
  "Metrics": [
    {
      "ObjectType": [ "VirtualMachine", "HostSystem" ],
      "Definition": [
        { "Metric": "cpu.usage.average", "Instances": "" },
        { "Metric": "cpu.usage.maximum", "Instances": "" },
        { "Metric": "cpu.usagemhz.average", "Instances": "" },
        { "Metric": "cpu.usagemhz.maximum", "Instances": "" },
        { "Metric": "cpu.totalCapacity.average", "Instances": "" },
        { "Metric": "mem.usage.average", "Instances": "" },
        { "Metric": "mem.usage.maximum", "Instances": "" },
        { "Metric": "mem.consumed.average", "Instances": "" },
        { "Metric": "mem.consumed.maximum", "Instances": "" },
        { "Metric": "mem.active.average", "Instances": "" },
        { "Metric": "mem.active.maximum", "Instances": "" },
        { "Metric": "mem.vmmemctl.average", "Instances": "" },
        { "Metric": "mem.vmmemctl.maximum", "Instances": "" },
		{ "Metric": "datastore.datastoreIops.average", "Instances": "" },
		{ "Metric": "datastore.datastoreNormalReadLatency.latest", "Instances": "" },
		{ "Metric": "datastore.datastoreNormalWriteLatency.latest", "Instances": "" },
        { "Metric": "mem.totalCapacity.average", "Instances": "" }
		

		
      ]
    },
    {
      "ObjectType": [ "VirtualMachine" ],
      "Definition": [
        { "Metric": "virtualDisk.totalWriteLatency.average", "Instances": "*" },
        { "Metric": "virtualDisk.totalWriteLatency.maximum", "Instances": "*" },
        { "Metric": "virtualDisk.totalReadLatency.average", "Instances": "*" },
        { "Metric": "virtualDisk.totalReadLatency.maximum", "Instances": "*" },
        { "Metric": "virtualDisk.numberReadAveraged.average", "Instances": "*" },
        { "Metric": "virtualDisk.numberWriteAveraged.average", "Instances": "*" }
      ]
    },
    {
      "ObjectType": [ "HostSystem" ],
      "Definition": [
        { "Metric": "disk.maxTotalLatency.latest", "Instances": "" },
        { "Metric": "disk.numberReadAveraged.average", "Instances": "*" },
        { "Metric": "disk.numberWriteAveraged.average", "Instances": "*" }
      ]
    }
  ]
}

**Comment by cblomart** [comment] 2017-05-21 14:51
Yes that is how to add metrics. Some metrics are only taken per instance, so puttint "*" in "Instances might be necessary.

**Comment by ridhoyp** [comment] 2017-05-22 03:17
Hi, 

this graphite is more awesome than the infludb-go, i will make the dashboard template with this

thankyou so much

Regards,
RidhoYP

**Comment by cblomart** [comment] 2017-05-29 20:52
Can i consider the issue closed?

**Comment by cblomart** [comment] 2017-06-06 09:02
As allways when closing without further comment, don't hesitate to comment if the issue is still present.

**Closed by cblomart** 2017-06-06 09:02 UTC
