### ISSUE TITLE
Graphana UI shows different things with different versions

### ISSUE THREAD

**Issue by scaleoutsean** [cblomart/vsphere-graphite#77] opened 2019-02-09 17:39 UTC
I changed several things at once (not a good idea). so it took me several hours to narrow this down a bit - it seems that a recent vsphere-graphite container works differently compared to 1-2 months ago.

`cblomart/vsphere-graphite:eaa6a13` results in no VMs but different things appearing in VM drop-down list.

![image](https://user-images.githubusercontent.com/16622642/52523243-4ab67c00-2cca-11e9-8547-8677145e04df.png)

`cblomart/vsphere-graphite:50ab88b` works fine.

![image](https://user-images.githubusercontent.com/16622642/52523991-aedd3e00-2cd2-11e9-8750-f6997b0aa975.png)

I used the two versions above with `graphiteapp/graphite-statsd:1.1.5-7` for graphite-statsd (which is the second major change in this case, as previously I used graphite-statsd v0.8.0). My vSphere/ESXi are v6.7.

cblomart/vsphere-graphite:50ab88b worked fine with the old graphite-statsd v0.8.0, but I haven't tested cblomart/vsphere-graphite:eaa6a13 with that old graphite-statsd version.

**Comment by cblomart** [comment] 2019-02-15 11:02
On your first screenshot it seems it takes performance metric names in place of vm names.

I presume you are using influxdb as a backend?

I will try to dublicate that in a lab...

**Comment by cblomart** [comment] 2019-02-21 12:49
As replied to #78 :

Ok, i tried to implement a limit on graphite and there was a bug in it preventing to collect names of entities.
The limit is in place as graphite doesn't have metadata and doesn't need to collect plentity of extra infromations from vsphere.

Can you test with [05a4dc5](https://github.com/cblomart/vsphere-graphite/commit/05a4dc5c2c852d84e1c03ce241e4be0382a5fd94) ?

**Comment by cblomart** [comment] 2019-02-22 15:08
Worked for the other issue. 
The problem should only have been present with graphite (and not with influx).

**Comment by cblomart** [comment] 2019-02-26 14:46
Hello @scaleoutsean did you have time to check if the problem is solved by the changes provided?

**Comment by scaleoutsean** [comment] 2019-02-27 14:50
Maxed out for many consecutive days. Will try this week or weekend and update this comment!

**Comment by cblomart** [comment] 2019-03-08 14:55
Ok... as the issue indicated earlier was realy impacting (vm names no longer collected) is solved... i will close the issue.

**Closed by cblomart** 2019-03-08 14:55 UTC

**Comment by scaleoutsean** [comment] 2019-10-26 23:18
Tried v0.8a release, works fine.
![image](https://user-images.githubusercontent.com/16622642/67627176-27a60b00-f80c-11e9-9a77-8e255aa6a842.png)
