### ISSUE TITLE
Getting data I don't expect

### ISSUE THREAD

**Issue by nward** [cblomart/vsphere-graphite#40] opened 2018-07-15 06:20 UTC
Hi!

I have two instances of vsphere-graphite running, with the exact same config. One is "production" one is "test" but they point at the same VC servers etc.

Weirdly, the two instance report slightly different data - for example, I request "virtualDisk.vFlashCacheIops.latest" for VirtualMachine object, but. none of my VMs have this available yet so I expect to not get data.

One of the two instances I mention reports data for this metric, the other does not - despite the configuration being identical. The "production" instance reports this, while the "test" instance does not.
Curiously, the value I get for the above (and other vFlash metrics) is completely off - on VMs which do almost zero disk IO, it reports 30k+ IOPS, following a curve of network traffic (the VM in question does VoIP call stuff, so lots of network, no disk IO). I am not sure where this is coming from.

I'm not really clear how to debug this - not a Go guy.

I did wonder if the metric mapping between the two VC servers was getting confused but it doesn't appear to be.

I have run some manual python queries against the API and there is no realtime or historical metrics for any VMs I have which return any virtualDisk.vFlash* metrics, so, something weird seems to be going on...!

**Comment by cblomart** [comment] 2018-07-15 19:12
few questions first:
Which version are you running (should be listed in the begining of logs? 
  * from a release?
  * from docker
  * did you build from golang (go get)

remark 1: i've been trying to simplify point management, this could be the cause but this change is not in any release so except if you run from "go get" or specificaly tagged docker, the issue is not there.

remark 2: these are latest values so they will be different from one daemon to the other, simply because time is different for each of them.

**Comment by cblomart** [comment] 2018-07-24 16:50
Hello, I will close this issue. I will reopen it with more information

**Closed by cblomart** 2018-07-24 16:50 UTC
